# Generated by Django 4.0.2 on 2022-02-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kennel_name', models.CharField(max_length=128)),
                ('kennel_is_active', models.BooleanField()),
                ('kennel_img_path', models.ImageField(null=True, upload_to='')),
                ('kennel_about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KennelLongevityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KennelURLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('url_desc', models.CharField(max_length=32)),
                ('url_kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kennels.kennel')),
            ],
        ),
        migrations.CreateModel(
            name='KennelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kennels.kennel')),
            ],
        ),
    ]
