# Generated by Django 4.0.2 on 2022-02-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_id_alter_city_region_and_more'),
        ('kennels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennelmembership',
            name='member_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AddField(
            model_name='kennellongevitylink',
            name='longevity_linked_kennel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longevity_linked_kennel', to='kennels.kennel'),
        ),
        migrations.AddField(
            model_name='kennellongevitylink',
            name='longevity_master_kennel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longevity_master_kennel', to='kennels.kennel'),
        ),
        migrations.AddField(
            model_name='kennel',
            name='kennel_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
    ]
