# Generated by Django 4.0.2 on 2022-03-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0002_alter_consensus_options_remove_consensus_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consensus',
            name='is_make_admin',
        ),
    ]
