# Generated by Django 4.0.2 on 2022-02-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0003_kennel_kennel_abbr_alter_kennel_kennel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kennel',
            name='kennel_about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kennel',
            name='kennel_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
