# Generated by Django 4.0.2 on 2022-02-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_event_end_time_and_more'),
        ('members', '0007_remove_member_member_kennels_and_more'),
        ('kennels', '0004_alter_kennel_kennel_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kennellongevitylink',
            name='longevity_linked_kennel',
        ),
        migrations.RemoveField(
            model_name='kennellongevitylink',
            name='longevity_master_kennel',
        ),
        migrations.RenameField(
            model_name='kennelmembership',
            old_name='member_kennel',
            new_name='membership_kennel',
        ),
        migrations.RenameField(
            model_name='kennelmembership',
            old_name='member_user',
            new_name='membership_member',
        ),
        migrations.AddField(
            model_name='kennel',
            name='kennel_events',
            field=models.ManyToManyField(through='events.EventHost', to='events.Event'),
        ),
        migrations.AddField(
            model_name='kennel',
            name='kennel_longevity_includes',
            field=models.ManyToManyField(to='kennels.Kennel'),
        ),
        migrations.AddField(
            model_name='kennel',
            name='kennel_members',
            field=models.ManyToManyField(related_name='member_kennels', through='kennels.KennelMembership', to='members.Member'),
        ),
        migrations.AddField(
            model_name='kennelmembership',
            name='membership_is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kennelmembership',
            name='membership_is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='kennelmembership',
            constraint=models.UniqueConstraint(fields=('membership_member', 'membership_kennel'), name='unique_membership_request'),
        ),
        migrations.DeleteModel(
            name='KennelLongevityLink',
        ),
    ]
