# Generated by Django 4.0.2 on 2022-03-10 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0005_kennel_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kennel',
            name='creator',
        ),
    ]
