# Generated by Django 4.0.2 on 2022-02-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0005_remove_kennellongevitylink_longevity_linked_kennel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kennel',
            name='kennel_city',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
