# Generated by Django 4.0.2 on 2022-03-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0006_remove_kennel_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consensusvote',
            name='vote',
            field=models.BooleanField(null=True),
        ),
    ]
