# Generated by Django 4.0.2 on 2022-02-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0006_alter_kennel_kennel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kennel',
            name='kennel_members',
        ),
    ]
