# Generated by Django 4.0.2 on 2022-02-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_invitecode_invite_expiration'),
        ('kennels', '0007_remove_kennel_kennel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennel',
            name='kennel_members',
            field=models.ManyToManyField(related_name='member_kennels', through='kennels.KennelMembership', to='members.Member'),
        ),
    ]
