# Generated by Django 4.0.2 on 2022-03-13 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_attend_claimants_alter_attendclaim_claimant'),
        ('kennels', '0007_alter_consensusvote_vote'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consensus',
            name='unique_consensus',
        ),
        migrations.AddField(
            model_name='consensus',
            name='event',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='events.event'),
        ),
        migrations.AlterField(
            model_name='consensus',
            name='initiator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='initiated_consensuses',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consensus',
            name='member',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='consensus',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('event__isnull', True),
                                        ('type__in', [0, 1, 2]),
                                        ('member__isnull', False)),
                               models.Q(('event__isnull', False),
                                        ('type__in', [3, 4]),
                                        ('member__isnull', True)),
                               _connector='OR'),
                name='consensus_type_constraint'),
        ),
        migrations.AddConstraint(
            model_name='consensus',
            constraint=models.UniqueConstraint(condition=models.Q(
                ('final_vote__isnull', True)),
                                               fields=('kennel', 'member'),
                                               name='unique_member_consensus'),
        ),
        migrations.AddConstraint(
            model_name='consensus',
            constraint=models.UniqueConstraint(condition=models.Q(
                ('final_vote__isnull', True)),
                                               fields=('kennel', 'event'),
                                               name='unique_event_consensus'),
        ),
    ]
