# Generated by Django 4.0.2 on 2022-02-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_member_kennels'),
        ('kennels', '0008_kennel_kennel_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kennel',
            name='kennel_members',
            field=models.ManyToManyField(through='kennels.KennelMembership', to='members.Member'),
        ),
    ]
