# Generated by Django 4.0.2 on 2022-02-28 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('members', '0013_alter_invitecode_invite_expiration'),
        ('kennels', '0010_rename_kennel_img_path_kennel_kennel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='KennelConsensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consensus_initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='KennelConsensusVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('vote_consensus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kennels.kennelconsensus')),
                ('vote_elector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.AddConstraint(
            model_name='kennelconsensusvote',
            constraint=models.UniqueConstraint(fields=('vote_consensus', 'vote_elector'), name='unique_consensus_vote'),
        ),
    ]
