# Generated by Django 4.0.2 on 2022-03-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0010_remove_consensus_unique_member_consensus_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consensus',
            name='unique_event_consensus',
        ),
    ]
