# Generated by Django 4.0.2 on 2022-02-28 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_invitecode_invite_expiration'),
        ('events', '0003_remove_event_event_end_time_and_more'),
        ('kennels', '0011_kennelconsensus_kennelconsensusvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KennelKickConsensus',
            fields=[
                ('kennelconsensus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kennels.kennelconsensus')),
                ('consensus_kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kennels.kennel')),
                ('consensus_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            bases=('kennels.kennelconsensus',),
        ),
        migrations.CreateModel(
            name='KennelDeleteConsensus',
            fields=[
                ('kennelconsensus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kennels.kennelconsensus')),
                ('consensus_kennel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kennels.kennel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kennels.kennelconsensus',),
        ),
        migrations.CreateModel(
            name='KennelAdminConsensus',
            fields=[
                ('kennelconsensus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kennels.kennelconsensus')),
                ('consensus_action', models.BooleanField()),
                ('consensus_kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kennels.kennel')),
                ('consensus_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            bases=('kennels.kennelconsensus',),
        ),
        migrations.CreateModel(
            name='EventDeleteConsensus',
            fields=[
                ('kennelconsensus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kennels.kennelconsensus')),
                ('consensus_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kennels.kennelconsensus',),
        ),
        migrations.AddConstraint(
            model_name='kennelkickconsensus',
            constraint=models.UniqueConstraint(fields=('consensus_kennel', 'consensus_member'), name='unique_kennel_kick_consensus'),
        ),
        migrations.AddConstraint(
            model_name='kenneladminconsensus',
            constraint=models.UniqueConstraint(fields=('consensus_kennel', 'consensus_member'), name='unique_kennel_admin_consensus'),
        ),
    ]
