# Generated by Django 4.0.2 on 2022-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0011_remove_consensus_unique_event_consensus_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consensus',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event__isnull', True), ('membership__isnull', False), ('type__in', [0, 1, 2])), models.Q(('event__isnull', False), ('membership__isnull', True), ('type__in', [3, 4])), _connector='OR'), name='consensus_type_constraint'),
        ),
        migrations.AddConstraint(
            model_name='consensus',
            constraint=models.UniqueConstraint(condition=models.Q(('final_vote__isnull', True)), fields=('kennel', 'membership'), name='unique_membership_consensus'),
        ),
        migrations.AddConstraint(
            model_name='consensus',
            constraint=models.UniqueConstraint(condition=models.Q(('final_vote__isnull', True)), fields=('kennel', 'event'), name='unique_event_consensus'),
        ),
    ]
