# Generated by Django 4.0.2 on 2022-02-28 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_event_end_time_and_more'),
        ('kennels', '0012_kennelkickconsensus_kenneldeleteconsensus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdeleteconsensus',
            name='consensus_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
