# Generated by Django 4.0.2 on 2022-03-01 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0013_alter_eventdeleteconsensus_consensus_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kenneladminconsensus',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='kennelkickconsensus',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveConstraint(
            model_name='kenneladminconsensus',
            name='unique_kennel_admin_consensus',
        ),
        migrations.RemoveConstraint(
            model_name='kennelkickconsensus',
            name='unique_kennel_kick_consensus',
        ),
        migrations.RemoveField(
            model_name='kenneladminconsensus',
            name='consensus_kennel',
        ),
        migrations.RemoveField(
            model_name='kenneldeleteconsensus',
            name='consensus_kennel',
        ),
        migrations.RemoveField(
            model_name='kennelkickconsensus',
            name='consensus_kennel',
        ),
        migrations.AddField(
            model_name='kennelconsensus',
            name='consensus_kennel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kennels.kennel'),
            preserve_default=False,
        ),
    ]
