# Generated by Django 4.0.2 on 2022-03-15 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kennels', '0014_remove_consensus_consensus_type_constraint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyLongevity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('hares', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='consensus',
            name='unique_membership_consensus',
        ),
        migrations.RemoveConstraint(
            model_name='consensus',
            name='unique_event_consensus',
        ),
        migrations.RemoveField(
            model_name='consensus',
            name='final_action',
        ),
        migrations.RemoveField(
            model_name='consensus',
            name='final_vote',
        ),
        migrations.AddConstraint(
            model_name='consensus',
            constraint=models.UniqueConstraint(fields=('kennel', 'membership'), name='unique_membership_consensus'),
        ),
        migrations.AddConstraint(
            model_name='consensus',
            constraint=models.UniqueConstraint(fields=('kennel', 'event'), name='unique_event_consensus'),
        ),
        migrations.AddField(
            model_name='legacylongevity',
            name='kennel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_longevity', to='kennels.kennel'),
        ),
        migrations.AddField(
            model_name='legacylongevity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_longevity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='legacylongevity',
            constraint=models.UniqueConstraint(fields=('user', 'kennel'), name='unique_legacy_longevity'),
        ),
    ]
