# Generated by Django 4.0.2 on 2022-02-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0002_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_kennels',
            field=models.ManyToManyField(through='kennels.KennelMembership', to='kennels.Kennel'),
        ),
    ]
