# Generated by Django 4.0.2 on 2022-02-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_member_kennels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='invite_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
