# Generated by Django 4.0.2 on 2022-02-22 01:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_invitecode_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='invite_expiration',
            field=models.DateField(default=datetime.date(2022, 3, 1)),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='invite_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_receiver', to='members.member'),
        ),
    ]
