# Generated by Django 4.0.2 on 2022-02-22 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_invitecode_invite_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='invite_expiration',
            field=models.DateField(default=datetime.date(2022, 3, 1), null=True),
        ),
    ]
