# Generated by Django 4.0.2 on 2022-02-24 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_invitecode_invite_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_kennels',
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='invite_expiration',
            field=models.DateField(default=datetime.date(2022, 3, 3), null=True),
        ),
        migrations.DeleteModel(
            name='MembershipRequest',
        ),
    ]
