# Generated by Django 4.0.2 on 2022-02-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_invitecode_invite_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_kennels',
            field=models.ManyToManyField(related_name='kennel_members', through='kennels.KennelMembership', to='members.Member'),
        ),
    ]
