# Generated by Django 4.0.2 on 2022-02-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_member_kennels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_kennels',
            field=models.ManyToManyField(blank=True, through='kennels.KennelMembership', to='members.Member'),
        ),
    ]
