# Generated by Django 4.0.2 on 2022-02-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0009_alter_kennel_kennel_members'),
        ('members', '0010_alter_member_member_kennels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_kennels',
            field=models.ManyToManyField(blank=True, through='kennels.KennelMembership', to='kennels.Kennel'),
        ),
    ]
