# Generated by Django 4.0.2 on 2022-02-27 01:21

import datetime
from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_member_member_kennels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='invite_expiration',
            field=models.DateField(default=datetime.date(2022, 3, 6), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_avatar',
            field=models.ImageField(null=True, upload_to=members.models.avatar_upload),
        ),
    ]
