# Generated by Django 4.0.2 on 2022-02-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128)),
                ('event_date', models.DateField()),
                ('event_start_time', models.TimeField(null=True)),
                ('event_end_time', models.TimeField(null=True)),
                ('event_desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_is_longevity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EventMemberAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_is_longevity', models.BooleanField()),
                ('attend_is_hare', models.BooleanField()),
                ('attend_note', models.TextField(blank=True)),
                ('attend_is_verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EventNonMemberAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_is_longevity', models.BooleanField()),
                ('attend_is_hare', models.BooleanField()),
                ('attend_note', models.TextField(blank=True)),
                ('attend_nonmember_name', models.CharField(max_length=32)),
                ('attend_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
