# Generated by Django 4.0.2 on 2022-03-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128)),
                ('event_date', models.DateField()),
                ('event_desc', models.TextField(blank=True)),
            ],
        ),
    ]
