# Generated by Django 4.0.2 on 2022-02-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
        ('kennels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnonmemberattend',
            name='attend_just_claim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
        migrations.AddField(
            model_name='eventmemberattend',
            name='attend_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='eventmemberattend',
            name='attend_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AddField(
            model_name='eventhost',
            name='host_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='eventhost',
            name='host_kennel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kennels.kennel'),
        ),
        migrations.AddConstraint(
            model_name='eventnonmemberattend',
            constraint=models.UniqueConstraint(fields=('attend_event', 'attend_nonmember_name'), name='unique_nonmember_attend'),
        ),
        migrations.AddConstraint(
            model_name='eventmemberattend',
            constraint=models.UniqueConstraint(fields=('attend_event', 'attend_member'), name='unique_member_attend'),
        ),
    ]
