# Generated by Django 4.0.2 on 2022-03-12 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_attend_longevity_longevityrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longevity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longevity', to='events.event'),
        ),
    ]
