# Generated by Django 4.0.2 on 2022-03-12 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kennels', '0007_alter_consensusvote_vote'),
        ('events', '0004_alter_longevity_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kennels',
            field=models.ManyToManyField(through='events.Longevity', to='kennels.Kennel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kennels.kennel'),
        ),
        migrations.AlterField(
            model_name='longevity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.CreateModel(
            name='AttendClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.attend')),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendclaim',
            constraint=models.UniqueConstraint(fields=('attend', 'claimant'), name='unique_attend_claim'),
        ),
    ]
