# Generated by Django 4.0.2 on 2022-03-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_kennels_alter_event_host_alter_longevity_event_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('name', 'host'), name='unique_kennel_event'),
        ),
    ]
