# Generated by Django 4.0.2 on 2022-03-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_attend_attend_not_claimed_and_unclaimed_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attend',
            name='attend_not_claimed_and_unclaimed',
        ),
        migrations.AddConstraint(
            model_name='attend',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('unclaimed_name__isnull', True), ('user__isnull', False)), models.Q(('unclaimed_name__isnull', False), ('user__isnull', True)), _connector='OR'), name='attend_not_claimed_and_unclaimed'),
        ),
    ]
