# Generated by Django 4.0.2 on 2022-03-13 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0008_remove_attend_attend_not_claimed_and_unclaimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='claimants',
            field=models.ManyToManyField(through='events.AttendClaim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendclaim',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
